// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dashboard} from '../models';
import {wsl} from '../models';
import {plugins} from '../models';

export function CheckDashboard():Promise<dashboard.DashboardStatus>;

export function CheckOpenClaw():Promise<wsl.OpenClawStatus>;

export function CheckWSL():Promise<wsl.WSLInfo>;

export function CheckWSLRunning():Promise<boolean>;

export function DisablePlugin(arg1:string):Promise<void>;

export function EnablePlugin(arg1:string):Promise<void>;

export function GetAvailableVersions():Promise<Record<string, any>>;

export function GetFeishuConfig():Promise<Record<string, any>>;

export function GetGatewayStatus():Promise<Record<string, any>>;

export function GetInitialState():Promise<Record<string, any>>;

export function GetModelsConfig():Promise<Record<string, any>>;

export function GetPluginDetail(arg1:string):Promise<string>;

export function GetPlugins():Promise<Array<plugins.Plugin>>;

export function GetProviderCatalog(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function InstallCustomPlugin(arg1:string):Promise<void>;

export function InstallOpenClaw():Promise<void>;

export function InstallPlugin(arg1:string):Promise<void>;

export function InstallUbuntu():Promise<void>;

export function InstallVersion(arg1:string):Promise<Record<string, any>>;

export function InstallWSL():Promise<Record<string, any>>;

export function OpenURL(arg1:string):Promise<void>;

export function RestartGateway():Promise<Record<string, any>>;

export function RunWSL():Promise<Record<string, any>>;

export function RunWSLAsync():Promise<void>;

export function SaveFeishuConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SaveModelsConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function StartGateway():Promise<Record<string, any>>;

export function StopGateway():Promise<Record<string, any>>;

export function StopGatewayLogs():Promise<Record<string, any>>;

export function StopWSL():Promise<Record<string, any>>;

export function StreamGatewayLogs():Promise<void>;

export function ToggleFeishuPlugin(arg1:boolean):Promise<Record<string, any>>;

export function UninstallOpenClaw():Promise<void>;

export function UninstallPlugin(arg1:string):Promise<void>;

export function WeixinAuth():Promise<void>;
