// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDashboard() {
  return window['go']['main']['App']['CheckDashboard']();
}

export function CheckOpenClaw() {
  return window['go']['main']['App']['CheckOpenClaw']();
}

export function CheckWSL() {
  return window['go']['main']['App']['CheckWSL']();
}

export function CheckWSLRunning() {
  return window['go']['main']['App']['CheckWSLRunning']();
}

export function DisablePlugin(arg1) {
  return window['go']['main']['App']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['App']['EnablePlugin'](arg1);
}

export function GetFeishuConfig() {
  return window['go']['main']['App']['GetFeishuConfig']();
}

export function GetGatewayStatus() {
  return window['go']['main']['App']['GetGatewayStatus']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetModelsConfig() {
  return window['go']['main']['App']['GetModelsConfig']();
}

export function GetPluginDetail(arg1) {
  return window['go']['main']['App']['GetPluginDetail'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetProviderCatalog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProviderCatalog'](arg1, arg2, arg3);
}

export function InstallCustomPlugin(arg1) {
  return window['go']['main']['App']['InstallCustomPlugin'](arg1);
}

export function InstallOpenClaw() {
  return window['go']['main']['App']['InstallOpenClaw']();
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function InstallUbuntu() {
  return window['go']['main']['App']['InstallUbuntu']();
}

export function InstallWSL() {
  return window['go']['main']['App']['InstallWSL']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RestartGateway() {
  return window['go']['main']['App']['RestartGateway']();
}

export function RunWSL() {
  return window['go']['main']['App']['RunWSL']();
}

export function RunWSLAsync() {
  return window['go']['main']['App']['RunWSLAsync']();
}

export function SaveFeishuConfig(arg1) {
  return window['go']['main']['App']['SaveFeishuConfig'](arg1);
}

export function SaveModelsConfig(arg1) {
  return window['go']['main']['App']['SaveModelsConfig'](arg1);
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function StopWSL() {
  return window['go']['main']['App']['StopWSL']();
}

export function ToggleFeishuPlugin(arg1) {
  return window['go']['main']['App']['ToggleFeishuPlugin'](arg1);
}

export function UninstallOpenClaw() {
  return window['go']['main']['App']['UninstallOpenClaw']();
}

export function UninstallPlugin(arg1) {
  return window['go']['main']['App']['UninstallPlugin'](arg1);
}

export function WeixinAuth() {
  return window['go']['main']['App']['WeixinAuth']();
}
